#!/bin/sh

### BEGIN INIT INFO
# Provides:          linuxsampler
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LinuxSampler
# Description:       LinuxSampler
### END INIT INFO

DAEMON="/usr/bin/linuxsampler"
DAEMON_NAME=linuxsampler
DAEMON_OPTS="--exec-after-init 'bin/netcat localhost 8888 < /etc/linuxsampler.conf'"
DAEMON_USER=pi
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --nicelevel -19 --iosched real-time --pidfile $PIDFILE --make-pidfile --startas /bin/bash -- -c "exec $DAEMON $DAEMON_OPTS"
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        sleep 1
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
